#!/bin/bash
# Generates a project-local .npmrc that routes @cookieyes packages to
# AWS CodeArtifact while keeping public npm as the default.
#
# Re-run this whenever the CodeArtifact token expires (every 12 hours).
#
# ⚠️  INTERNAL USE ONLY — contains shared read-only AWS credentials.
# Do NOT commit to a public repo, do NOT forward externally.

set -euo pipefail

# ─── Config ────────────────────────────────────────────────────────────
AWS_REGION="eu-west-1"
DOMAIN="cookieyes"
DOMAIN_OWNER="275032138359"
REPO="consent-sdk-alpha"
SCOPE="@cookieyes"
NPMRC_PATH=".npmrc"

# Read-only IAM user — scoped to the consent-sdk-alpha repo only.
# Get these from the SDK maintainer (Saurav <saurav@mozilor.com>).
AWS_ACCESS_KEY_ID="REPLACE_WITH_AKIA…"
AWS_SECRET_ACCESS_KEY="REPLACE_WITH_SECRET"
# ───────────────────────────────────────────────────────────────────────

command -v aws >/dev/null 2>&1 || { echo "❌ AWS CLI not found. Install: brew install awscli"; exit 2; }
command -v npm >/dev/null 2>&1 || { echo "❌ npm not found. Install Node.js first."; exit 3; }

if [[ "$AWS_ACCESS_KEY_ID" == REPLACE_* ]] || [[ "$AWS_SECRET_ACCESS_KEY" == REPLACE_* ]]; then
  echo "❌ AWS keys not set. Open scripts/codeartifact-login.sh and fill in the values from the SDK maintainer."
  exit 1
fi

REGISTRY_HOST="${DOMAIN}-${DOMAIN_OWNER}.d.codeartifact.${AWS_REGION}.amazonaws.com"
REGISTRY_URL="https://${REGISTRY_HOST}/npm/${REPO}/"

TMP_CREDS_FILE="$(mktemp -t cookieyes-creds.XXXXXX)"
chmod 600 "$TMP_CREDS_FILE"
cat > "$TMP_CREDS_FILE" <<EOF
[default]
aws_access_key_id = ${AWS_ACCESS_KEY_ID}
aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}
EOF

cleanup() {
  if [ -f "$TMP_CREDS_FILE" ]; then
    if command -v shred >/dev/null 2>&1; then
      shred -u -z "$TMP_CREDS_FILE" 2>/dev/null || rm -f "$TMP_CREDS_FILE"
    else
      rm -f "$TMP_CREDS_FILE"
    fi
  fi
}
trap cleanup EXIT INT TERM

export AWS_SHARED_CREDENTIALS_FILE="$TMP_CREDS_FILE"
export AWS_DEFAULT_REGION="$AWS_REGION"
unset AWS_PROFILE AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN

echo "🔎 Fetching CodeArtifact token (12h TTL)..."
TOKEN=$(aws codeartifact get-authorization-token \
  --domain "$DOMAIN" \
  --domain-owner "$DOMAIN_OWNER" \
  --region "$AWS_REGION" \
  --query authorizationToken \
  --output text)

if [ -z "$TOKEN" ] || [ "$TOKEN" = "None" ]; then
  echo "❌ Failed to fetch token. Contact the SDK maintainer."
  exit 5
fi

echo "📝 Writing ${NPMRC_PATH}..."
cat > "$NPMRC_PATH" <<EOF
# Auto-generated by scripts/codeartifact-login.sh — do NOT commit.
# Token expires 12 hours after the last run.

registry=https://registry.npmjs.org/
${SCOPE}:registry=${REGISTRY_URL}
//${REGISTRY_HOST}/npm/${REPO}/:_authToken=${TOKEN}
//${REGISTRY_HOST}/npm/${REPO}/:always-auth=true
EOF

chmod 600 "$NPMRC_PATH"

echo "✅ .npmrc written. Now run: npm install"
echo "   ⏱  Re-run this script every 12h when the token expires."
